# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-14 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lianjiatenementhouse',
            name='platform',
            field=models.CharField(default='链家网', max_length=6),
        ),
    ]
